// libs/lyra-sheet-react/src/lib/components/actions/StrikeAction.tsx
import { ReactComponent as Strike } from '../../icons/strikethrough.svg';
import { useEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../../container-context';
import { FontStrikeController } from '@lyra-sheet/core';

export function LyraSheetStrikeAction() {
  const ref = useRef<HTMLDivElement>(null);
  const controller = useLyraSheetCore(FontStrikeController);
  const [isStrike, setIsStrike] = useState(false);

  useEffect(() => {
    controller.value$.subscribe((res) => setIsStrike(res));
    controller.onInit();
    ref.current!.onmousedown = (evt) => evt.preventDefault();
  }, []);

  function applyTextItalic() {
    controller.toggle();
  }

  return (
    <div
      className={`lyra-sheet-toolbar-item ${isStrike ? 'activated' : ''}`}
      ref={ref}
      onClick={() => applyTextItalic()}
    >
      <Strike className={'lyra-sheet-toolbar-icon'}></Strike>
    </div>
  );
}

// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/strike-action/strike-action.component.ts
import {
  Component,
  ElementRef,
  HostBinding,
  HostListener,
  OnInit,
} from '@angular/core';
import { BaseContainer } from '../../../../services/_base_container';
import { FontStrikeController } from '@lyra-sheet/core';

@Component({
  selector: 'lyra-sheet-strike-action',
  templateUrl: './strike-action.component.html',
  styleUrls: ['./strike-action.component.scss'],
})
export class StrikeActionComponent implements OnInit {
  controller: FontStrikeController;
  @HostBinding('class.activated') isStrike = false;

  constructor(private el: ElementRef, private c: BaseContainer) {
    this.controller = c.fontStrikeController;
  }

  @HostListener('click')
  onClick(): void {
    this.controller.toggle();
  }

  ngOnInit(): void {
    this.controller.value$.subscribe((res) => (this.isStrike = res));
    this.controller.onInit();
    this.el.nativeElement.onmousedown = (evt: MouseEvent) =>
      evt.preventDefault();
  }
}

<i class="lyra-sheet-toolbar-icon strike-icon"></i>
