// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/bold-action/bold-action.component.ts
import {
  Component,
  ElementRef,
  HostBinding,
  HostListener,
  OnInit,
} from '@angular/core';
import { BaseContainer } from '../../../../services/_base_container';
import { FontBoldController } from '@lyra-sheet/core';

@Component({
  selector: 'lyra-sheet-bold-action',
  templateUrl: './bold-action.component.html',
  styleUrls: ['./bold-action.component.scss'],
})
export class BoldActionComponent implements OnInit {
  controller: FontBoldController;
  @HostBinding('class.activated') isBold = false;

  constructor(private c: BaseContainer, private el: ElementRef) {
    this.controller = c.fontBoldController;
  }

  @HostListener('click')
  onClick(): void {
    this.controller.toggle();
  }

  ngOnInit(): void {
    this.controller.value$.subscribe((res) => (this.isBold = res));
    this.controller.onInit();
    this.el.nativeElement.onmousedown = (evt: MouseEvent) =>
      evt.preventDefault();
  }
}

<i class="lyra-sheet-toolbar-icon bold-icon"></i>

// libs/lyra-sheet-react/src/lib/components/actions/BoldAction.tsx
import { ReactComponent as Bold } from '../../icons/text-bold.svg';
import { useEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../../container-context';
import { FontBoldController } from '@lyra-sheet/core';

export function LyraSheetBoldAction() {
  const ref = useRef<HTMLDivElement>(null);
  const controller = useLyraSheetCore(FontBoldController);
  const [isBold, setIsBold] = useState(false);

  useEffect(() => {
    controller.value$.subscribe((res) => setIsBold(res));
    controller.onInit();
    ref.current!.onmousedown = (evt) => evt.preventDefault();
  }, []);

  function applyTextBold() {
    controller.toggle();
  }

  return (
    <div
      className={`lyra-sheet-toolbar-item ${isBold ? 'activated' : ''}`}
      ref={ref}
      onClick={() => applyTextBold()}
    >
      <Bold className={'lyra-sheet-toolbar-icon'}></Bold>
    </div>
  );
}
