// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/font-color-dropdown/font-color-dropdown.component.ts
import { Component, ElementRef, OnInit } from '@angular/core';
import { DEFAULT_FONT_COLOR, FontColorController } from '@lyra-sheet/core';
import { BaseContainer } from '../../../../services/_base_container';

@Component({
  selector: 'lyra-sheet-font-color-dropdown',
  templateUrl: './font-color-dropdown.component.html',
  styleUrls: ['./font-color-dropdown.component.scss'],
})
export class FontColorDropdownComponent implements OnInit {
  controller: FontColorController;
  isOpen = false;
  curFontColor = DEFAULT_FONT_COLOR;

  constructor(private el: ElementRef, private c: BaseContainer) {
    this.controller = c.fontColorController;
    el.nativeElement.onmousedown = (evt: MouseEvent) => evt.preventDefault();
  }

  ngOnInit() {
    this.controller.curColor$.subscribe((res) => (this.curFontColor = res));
    this.controller.onInit();
  }

  applyTextColor(color: string): void {
    this.controller.applyTextColor(color);
    this.isOpen = false;
  }
}

<lyra-sheet-dropdown [dropdown]="colorPalette" [(isOpen)]="isOpen">
  <div style="width: 18px">
    <div style="text-align: center">A</div>
    <div
      style="height: 3px; width: 100%"
      [ngStyle]="{ backgroundColor: curFontColor }"
    ></div>
  </div>
</lyra-sheet-dropdown>
<ng-template #colorPalette>
  <div class="lyra-sheet-color-palette">
    <lyra-sheet-color-palette
      (chosenColor)="applyTextColor($event)"
    ></lyra-sheet-color-palette>
  </div>
</ng-template>

// libs/lyra-sheet-react/src/lib/components/actions/FontColorDropdown.tsx
import { useEffect, useRef, useState } from 'react';
import { LyraSheetDropdown } from '../Dropdown';
import { LyraSheetColorPalette } from '../ColorPalette';
import { DEFAULT_FONT_COLOR, FontColorController } from '@lyra-sheet/core';
import { useLyraSheetCore } from '../../container-context';

export function LyraSheetFontColorDropdown() {
  const controller = useLyraSheetCore(FontColorController);
  const hostRef = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState<boolean>(false);
  const [curFontColor, setCurFontColor] = useState(DEFAULT_FONT_COLOR);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  useEffect(() => {
    controller.curColor$.subscribe((res) => setCurFontColor(res));
    controller.onInit();
    hostRef.current!.onmousedown = (evt) => evt.preventDefault();
  }, []);

  function applyTextColor(color: string) {
    controller.applyTextColor(color);
    handleClose();
  }

  return (
    <div className={'lyra-sheet-toolbar-item'} ref={hostRef}>
      <LyraSheetDropdown
        isOpen={open}
        label={
          <div style={{ width: '18px' }}>
            <div style={{ textAlign: 'center' }}>A</div>
            <div
              style={{
                height: '3px',
                width: '100%',
                backgroundColor: curFontColor,
              }}
            ></div>
          </div>
        }
        onClose={handleClose}
        onOpen={handleOpen}
      >
        <div className={'lyra-sheet-color-palette'}>
          <LyraSheetColorPalette
            chosenColor={applyTextColor}
          ></LyraSheetColorPalette>
        </div>
      </LyraSheetDropdown>
    </div>
  );
}
