// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/text-wrap-dropdown/text-wrap-dropdown.component.ts
import { Component, OnInit } from '@angular/core';
import { TextWrapController, TextWrapType } from '@lyra-sheet/core';
import { BaseContainer } from '../../../../services/_base_container';

@Component({
  selector: 'lyra-sheet-text-wrap-dropdown',
  templateUrl: './text-wrap-dropdown.component.html',
  styleUrls: ['./text-wrap-dropdown.component.scss'],
})
export class TextWrapDropdownComponent implements OnInit {
  controller: TextWrapController;
  open = false;
  constructor(private c: BaseContainer) {
    this.controller = c.textWrapController;
  }

  ngOnInit() {
    this.controller.onInit();
  }

  selectTextWrap(type: TextWrapType): void {
    this.open = false;
    this.controller.applyTextWrap(type);
  }
}

<lyra-sheet-dropdown [dropdown]="dropdown" [(isOpen)]="open">
  <i
    class="lyra-sheet-toolbar-icon icon-text-{{
      controller.currentWrap$ | async
    }}"
  ></i>
</lyra-sheet-dropdown>

<ng-template #dropdown>
  <div class="lyra-sheet-dropdown-option" (click)="selectTextWrap('overflow')">
    <i class="lyra-sheet-toolbar-icon icon-text-overflow"></i>
  </div>
  <div class="lyra-sheet-dropdown-option" (click)="selectTextWrap('wrap')">
    <i class="lyra-sheet-toolbar-icon icon-text-wrap"></i>
  </div>
  <div class="lyra-sheet-dropdown-option" (click)="selectTextWrap('clip')">
    <i class="lyra-sheet-toolbar-icon icon-text-clip"></i>
  </div>
</ng-template>

// libs/lyra-sheet-react/src/lib/components/actions/TextWrapDropdown.tsx
import { LyraSheetDropdown } from '../Dropdown';
import { useLyraSheetCore } from '../../container-context';
import { TextValignDir, TextWrapController } from '@lyra-sheet/core';
import type { TextWrapType } from '@lyra-sheet/core';
import { useEffect, useState } from 'react';
import { ReactComponent as TextClip } from '../../icons/text-truncation.svg';
import { ReactComponent as TextWrap } from '../../icons/text-wrap.svg';
import { ReactComponent as TextOverflow } from '../../icons/text-overflow.svg';

export function LyraSheetTextWrapDropdown() {
  const controller = useLyraSheetCore(TextWrapController);
  const [currentWrap, setCurrentWrap] = useState<TextWrapType>('overflow');
  const [open, setOpen] = useState<boolean>(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  useEffect(() => {
    controller.currentWrap$.subscribe((val) => setCurrentWrap(val));
    controller.onInit();
  });

  function getLabel() {
    switch (currentWrap) {
      case 'clip':
        return <TextClip className={'lyra-sheet-toolbar-icon'} />;
      case 'wrap':
        return <TextWrap className={'lyra-sheet-toolbar-icon'} />;
      case 'overflow':
      default:
        return <TextOverflow className={'lyra-sheet-toolbar-icon'} />;
    }
  }

  function applyTextWrap(type: TextWrapType) {
    controller.applyTextWrap(type);
  }

  return (
    <div className={'lyra-sheet-toolbar-item'}>
      <LyraSheetDropdown
        isOpen={open}
        label={getLabel()}
        onClose={handleClose}
        onOpen={handleOpen}
      >
        <div
          className={'lyra-sheet-dropdown-option'}
          onClick={() => applyTextWrap('overflow')}
        >
          <TextOverflow className={'lyra-sheet-toolbar-icon'} />
        </div>
        <div
          className={'lyra-sheet-dropdown-option'}
          onClick={() => applyTextWrap('wrap')}
        >
          <TextWrap className={'lyra-sheet-toolbar-icon'} />
        </div>
        <div
          className={'lyra-sheet-dropdown-option'}
          onClick={() => applyTextWrap('clip')}
        >
          <TextClip className={'lyra-sheet-toolbar-icon'} />
        </div>
      </LyraSheetDropdown>
    </div>
  );
}
