// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/underline-action/underline-action.component.ts
import {
  Component,
  ElementRef,
  HostBinding,
  HostListener,
  OnInit,
} from '@angular/core';
import { BaseContainer } from '../../../../services/_base_container';
import { FontUnderlineController } from '@lyra-sheet/core';

@Component({
  selector: 'lyra-sheet-underline-action',
  templateUrl: './underline-action.component.html',
  styleUrls: ['./underline-action.component.scss'],
})
export class UnderlineActionComponent implements OnInit {
  controller: FontUnderlineController;
  @HostBinding('class.activated') isUnderlineNow = false;

  constructor(private el: ElementRef, private c: BaseContainer) {
    this.controller = c.fontUnderlineController;
  }

  @HostListener('click')
  onClick(): void {
    this.controller.toggle();
  }

  ngOnInit(): void {
    this.controller.value$.subscribe((res) => (this.isUnderlineNow = res));
    this.controller.onInit();
    this.el.nativeElement.onmousedown = (evt: MouseEvent) =>
      evt.preventDefault();
  }
}

<i class="lyra-sheet-toolbar-icon underline-icon"></i>

// libs/lyra-sheet-react/src/lib/components/actions/UnderlineAction.tsx
import { ReactComponent as Underline } from '../../icons/text-underline.svg';
import { useEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../../container-context';
import { FontUnderlineController } from '@lyra-sheet/core';

export function LyraSheetUnderlineAction() {
  const ref = useRef<HTMLDivElement>(null);
  const controller = useLyraSheetCore(FontUnderlineController);
  const [isUnderline, setIsUnderline] = useState(false);

  useEffect(() => {
    controller.value$.subscribe((res) => setIsUnderline(res));
    controller.onInit();
    ref.current!.onmousedown = (evt) => evt.preventDefault();
  }, []);

  function applyTextItalic() {
    controller.toggle();
  }

  return (
    <div
      className={`lyra-sheet-toolbar-item ${isUnderline ? 'activated' : ''}`}
      ref={ref}
      onClick={() => applyTextItalic()}
    >
      <Underline className={'lyra-sheet-toolbar-icon'}></Underline>
    </div>
  );
}
