// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/valign-dropdown/valign-dropdown.component.ts
import { Component, OnInit } from '@angular/core';
import { TextValignDir, ValignController } from '@lyra-sheet/core';
import { BaseContainer } from '../../../../services/_base_container';

@Component({
  selector: 'lyra-sheet-valign-dropdown',
  templateUrl: './valign-dropdown.component.html',
  styleUrls: ['./valign-dropdown.component.scss'],
})
export class ValignDropdownComponent implements OnInit {
  controller: ValignController;
  isOpen = false;
  constructor(private c: BaseContainer) {
    this.controller = c.valignController;
  }

  ngOnInit() {
    this.controller.onInit();
  }

  applyTextValign(dir: TextValignDir): void {
    this.isOpen = false;
    this.controller.applyTextValign(dir);
  }
}

<lyra-sheet-dropdown [dropdown]="dropdownTmpl" [(isOpen)]="isOpen">
  <i
    [ngClass]="[
      'lyra-sheet-toolbar-icon',
      'valign-' + (controller.currentDir$ | async) + '-icon'
    ]"
  ></i>
</lyra-sheet-dropdown>

<ng-template #dropdownTmpl>
  <div class="lyra-sheet-dropdown-option" (click)="applyTextValign('bottom')">
    <i class="lyra-sheet-toolbar-icon valign-bottom-icon"></i>
  </div>
  <div class="lyra-sheet-dropdown-option" (click)="applyTextValign('center')">
    <i class="lyra-sheet-toolbar-icon valign-center-icon"></i>
  </div>
  <div class="lyra-sheet-dropdown-option" (click)="applyTextValign('top')">
    <i class="lyra-sheet-toolbar-icon valign-top-icon"></i>
  </div>
</ng-template>

// libs/lyra-sheet-react/src/lib/components/actions/ValignDropdown.tsx
import { useLyraSheetCore } from '../../container-context';
import { ValignController } from '@lyra-sheet/core';
import type { TextValignDir } from '@lyra-sheet/core';
import { useEffect, useState } from 'react';
import { ReactComponent as ValignBottom } from '../../icons/底对齐_align-bottom.svg';
import { ReactComponent as ValignCenter } from '../../icons/垂直对齐_align-vertically.svg';
import { ReactComponent as ValignTop } from '../../icons/顶对齐_align-top.svg';
import { LyraSheetDropdown } from '../Dropdown';

export function LyraSheetValignDropdown() {
  const controller = useLyraSheetCore(ValignController);
  const [currentDir, setCurrentDir] = useState<TextValignDir>('bottom');
  const [open, setOpen] = useState<boolean>(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  useEffect(() => {
    controller.currentDir$.subscribe((res) => setCurrentDir(res));
    controller.onInit();
  });

  function getLabel() {
    switch (currentDir) {
      case 'center':
        return <ValignCenter className={'lyra-sheet-toolbar-icon'} />;
      case 'top':
        return <ValignTop className={'lyra-sheet-toolbar-icon'} />;
      case 'bottom':
      default:
        return <ValignBottom className={'lyra-sheet-toolbar-icon'} />;
    }
  }

  function applyTextValign(dir: TextValignDir): void {
    controller.applyTextValign(dir);
    handleClose();
  }

  return (
    <div className={'lyra-sheet-toolbar-item'}>
      <LyraSheetDropdown
        isOpen={open}
        label={getLabel()}
        onClose={handleClose}
        onOpen={handleOpen}
      >
        <div
          onClick={() => applyTextValign('bottom')}
          className={'lyra-sheet-dropdown-option'}
        >
          <ValignBottom className={'lyra-sheet-toolbar-icon'} />
        </div>
        <div
          onClick={() => applyTextValign('center')}
          className={'lyra-sheet-dropdown-option'}
        >
          <ValignCenter className={'lyra-sheet-toolbar-icon'} />
        </div>
        <div
          onClick={() => applyTextValign('top')}
          className={'lyra-sheet-dropdown-option'}
        >
          <ValignTop className={'lyra-sheet-toolbar-icon'} />
        </div>
      </LyraSheetDropdown>
    </div>
  );
}
