// libs/lyra-sheet-react/src/lib/components/actions/FontFamilyDropdown.tsx
import { LyraSheetDropdown } from '../Dropdown';
import { useEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../../container-context';
import { FontFamilyController } from '@lyra-sheet/core';
import { LyraSheetDropdownBar } from '../DropdownBar';

interface FFMenu {
  label: string;
  checked: boolean;
}

export function LyraSheetFontFamilyDropdown() {
  const hostRef = useRef<HTMLDivElement>(null);
  const controller = useLyraSheetCore(FontFamilyController);
  const [open, setOpen] = useState<boolean>(false);
  const [curFontFamily, setCurFontFamily] = useState<string>('');
  const [menus, setMenus] = useState<FFMenu[]>([]);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  useEffect(() => {
    hostRef.current!.onmousedown = (evt) => evt.preventDefault();
    controller.fontFamily$.subscribe((res) => setCurFontFamily(res));
    controller.allFontFamilies$.subscribe((res) => setMenus(res));
    controller.onInit();
  }, []);

  function applyFontFamily(ff: string) {
    controller.applyFontFamily(ff);
    handleClose();
  }

  return (
    <div className={'lyra-sheet-toolbar-item'} ref={hostRef}>
      <LyraSheetDropdown
        isOpen={open}
        label={curFontFamily}
        onClose={handleClose}
        onOpen={handleOpen}
      >
        {menus.map((menu) => (
          <LyraSheetDropdownBar
            key={menu.label}
            checked={menu.checked}
            onClick={() => applyFontFamily(menu.label)}
          >
            {menu.label}
          </LyraSheetDropdownBar>
        ))}
      </LyraSheetDropdown>
    </div>
  );
}

// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/font-family-dropdown/font-family-dropdown.component.ts
import { Component, ElementRef, OnInit } from '@angular/core';
import { FontFamilyController } from '@lyra-sheet/core';
import { BaseContainer } from '../../../../services/_base_container';

interface FFMenu {
  label: string;
  checked: boolean;
}

@Component({
  selector: 'lyra-sheet-font-family-dropdown',
  templateUrl: './font-family-dropdown.component.html',
  styleUrls: ['./font-family-dropdown.component.scss'],
})
export class FontFamilyDropdownComponent implements OnInit {
  controller: FontFamilyController;

  open = false;
  fontFamily = '';
  allFontFamilies: FFMenu[] = [];

  constructor(private el: ElementRef, private c: BaseContainer) {
    this.controller = this.c.fontFamilyController;
    el.nativeElement.onmousedown = (evt: MouseEvent) => evt.preventDefault();
  }

  ngOnInit() {
    this.controller.fontFamily$.subscribe((res) => (this.fontFamily = res));
    this.controller.allFontFamilies$.subscribe(
      (res) => (this.allFontFamilies = res),
    );
    this.controller.onInit();
  }

  applyFontFamily(ff: string): void {
    this.controller.applyFontFamily(ff);
    this.open = false;
  }
}

<lyra-sheet-dropdown [dropdown]="familyTmpl" [(isOpen)]="open">
  {{ fontFamily }}
</lyra-sheet-dropdown>
<ng-template #familyTmpl>
  <lyra-sheet-dropdown-bar
    *ngFor="let op of allFontFamilies"
    [checked]="op.checked"
    (click)="applyFontFamily(op.label)"
    [ngStyle]="{ fontFamily: op.label }"
  >
    {{ op.label }}
  </lyra-sheet-dropdown-bar>
</ng-template>
