// libs/lyra-sheet-react/src/lib/components/ResizerRow.tsx
import { useLayoutEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../container-context';
import {
  ConfigService,
  ElementRefService,
  MouseEventService,
  ResizerService,
  ResizerThickness,
} from '@lyra-sheet/core';

export function LyraSheetResizerRow() {
  const resizerRef = useRef<HTMLDivElement>(null);
  const resizerService = useLyraSheetCore(ResizerService);
  const configService = useLyraSheetCore(ConfigService);
  const elementRefService = useLyraSheetCore(ElementRefService);
  const mouseEventService = useLyraSheetCore(MouseEventService);

  const [isRowResizing, setIsRowResizing] = useState(false);

  const staticStyle = {
    height: `${ResizerThickness}px`,
    width: `${configService.ciw}px`,
  };

  const lineStyle = {
    width: `calc(100% - ${configService.ciw}px)`,
    transform: `translateY(-${Math.ceil(ResizerThickness / 2)}px)`,
  };

  useLayoutEffect(() => {
    mouseEventService.isRowResizing$.subscribe((res) => setIsRowResizing(res));
    elementRefService.initRowResizer(resizerRef.current!);
    resizerService.rowResizer$.subscribe((top) => {
      if (top === null) {
        resizerRef.current!.style.display = 'none';
      } else {
        resizerRef.current!.style.display = 'block';
        resizerRef.current!.style.top = `${top}px`;
      }
    });
  }, []);
  return (
    <div
      className={'lyra-sheet-resizer lyra-sheet-resizer-row'}
      ref={resizerRef}
    >
      <div className={'lyra-sheet-resizer-header'} style={staticStyle}></div>
      {isRowResizing ? (
        <div className={'lyra-sheet-resizer-row-line'} style={lineStyle}></div>
      ) : null}
    </div>
  );
}

// projects/ngx-datasheet/src/lib/components/resizer-row/resizer-row.component.ts
import { Component, ElementRef, OnInit } from '@angular/core';
import { ResizerThickness } from '../../constants';
import { ResizerService } from '../../service/resizer.service';
import { ConfigService } from '../../core/config.service';
import { MouseEventService } from '../../service/mouse-event.service';

@Component({
  selector: 'nd-resizer-row',
  templateUrl: './resizer-row.component.html',
  styleUrls: ['./resizer-row.component.less'],
  host: {
    class: 'nd-resizer nd-resizer-row',
  },
})
export class ResizerRowComponent implements OnInit {
  readonly staticStyle = {
    height: `${ResizerThickness}px`,
    width: `${this.configService.ciw}px`,
  };

  readonly lineStyle = {
    width: `calc(100% - ${this.configService.ciw}px)`,
    transform: `translateY(-${Math.ceil(ResizerThickness / 2)}px)`,
  };
  constructor(
    private el: ElementRef<HTMLElement>,
    private resizerService: ResizerService,
    private configService: ConfigService,
    public mouseEventService: MouseEventService,
  ) {}

  ngOnInit(): void {
    this.resizerService.rowResizer$.subscribe((top) => {
      if (top === null) {
        this.el.nativeElement.style.display = 'none';
      } else {
        this.el.nativeElement.style.display = 'block';
        this.el.nativeElement.style.top = `${top}px`;
      }
    });
  }
}

<div class="nd-resizer-header" [ngStyle]="staticStyle"></div>
<div
  *ngIf="mouseEventService.isRowResizing"
  class="nd-resizer-row-line"
  [ngStyle]="lineStyle"
></div>
