// libs/lyra-sheet-react/src/lib/components/SelectorContainer.tsx
import { useEffect, useRef, useState, Fragment } from 'react';
import {
  AutofillService,
  ConfigService,
  DataService,
  LocatedRect,
  ResizerService,
  ScrollingService,
  ViewRangeService,
} from '@lyra-sheet/core';
import { combineLatest } from 'rxjs';
import { useLyraSheetCore } from '../container-context';

export function LyraSheetSelectorContainer() {
  const containerRef = useRef<HTMLDivElement>(null);
  const [rects, setRects] = useState<LocatedRect[]>([]);
  const [autofillRect, setAutofillRect] = useState<LocatedRect | null>(null);
  const dataService = useLyraSheetCore(DataService);
  const resizerService = useLyraSheetCore(ResizerService);
  const scrollingService = useLyraSheetCore(ScrollingService);
  const viewRangeService = useLyraSheetCore(ViewRangeService);
  const configService = useLyraSheetCore(ConfigService);
  const autofillService = useLyraSheetCore(AutofillService);
  useEffect(() => {
    containerRef.current!.style.left = `${configService.ciw}px`;
    containerRef.current!.style.top = `${configService.rih}px`;
    combineLatest([
      dataService.selectorChanged$,
      // todo: can be optimized into resizerFinished$
      resizerService.colResizer$,
      resizerService.rowResizer$,
      scrollingService.scrolled$,
    ]).subscribe(([selectors]) => {
      const newRects = selectors.map((s) =>
        viewRangeService.locateRect(s.range),
      );
      setRects(newRects);
    });

    autofillService.autofillChanged$.subscribe((rect) => {
      if (rect) {
        setAutofillRect(viewRangeService.locateRect(rect));
      } else {
        setAutofillRect(null);
      }
    });
  }, []);

  return (
    <div
      className={'lyra-sheet-selector-container'}
      ref={containerRef}
      style={{ left: '60px', top: '25px' }}
    >
      {rects.map((r, index) => (
        <Fragment key={index}>
          <div
            className={'lyra-sheet-selector'}
            style={{
              top: r.top + 'px',
              left: r.left + 'px',
              width: r.width + 'px',
              height: r.height + 'px',
            }}
          ></div>
          <div
            className={'lyra-sheet-selector-autofill'}
            style={{
              top: r.top + r.height - 4 + 'px',
              left: r.left + r.width - 4 + 'px',
            }}
          ></div>
        </Fragment>
      ))}
      {autofillRect ? (
        <div
          className={'lyra-sheet-autofill'}
          style={{
            top: autofillRect.top + 'px',
            left: autofillRect.left + 'px',
            width: autofillRect.width + 'px',
            height: autofillRect.height + 'px',
          }}
        ></div>
      ) : null}
    </div>
  );
}

// projects/ngx-datasheet/src/lib/components/selector-container/selector-container.component.ts
import { Component, ElementRef, HostBinding, OnInit } from '@angular/core';
import { SelectorsService } from '../../core/selectors.service';
import { ViewRangeService } from '../../core/view-range.service';
import { combineLatest } from 'rxjs';
import { ResizerService } from '../../service/resizer.service';
import { LocatedRect } from '../../models';
import { AutofillService } from '../../service/autofill.service';
import { ScrollingService } from '../../core/scrolling.service';

@Component({
  selector: 'nd-selector-container',
  templateUrl: './selector-container.component.html',
  styleUrls: ['./selector-container.component.less'],
})
export class SelectorContainerComponent implements OnInit {
  @HostBinding('class.nd-selector-container') h = true;

  rects: LocatedRect[] = [];
  autofillRect: LocatedRect | null = null;

  constructor(
    private selectorRangeService: SelectorsService,
    public a: AutofillService,
    public v: ViewRangeService,
    private el: ElementRef<HTMLElement>,
    private r: ResizerService,
    private s: ScrollingService,
  ) {
    this.el.nativeElement.style.left = '60px';
    this.el.nativeElement.style.top = '25px';
  }

  ngOnInit(): void {
    combineLatest([
      this.selectorRangeService.selectorChanged,
      // todo: can be optimized into resizerFinished$
      this.r.colResizer$,
      this.r.rowResizer$,
      this.s.scrolled$,
    ]).subscribe(([selectors]) => {
      this.rects = selectors.map((s) => this.v.locateRect(s.range));
    });

    this.a.autofillChanged$.subscribe((rect) => {
      if (rect) {
        this.autofillRect = this.v.locateRect(rect);
      } else {
        this.autofillRect = null;
      }
    });
  }
}

<ng-container *ngFor="let r of rects">
  <div
    class="nd-selector"
    [ngStyle]="{
      top: r.top + 'px',
      left: r.left + 'px',
      width: r.width + 'px',
      height: r.height + 'px'
    }"
  ></div>
  <div
    class="nd-selector-autofill"
    [ngStyle]="{
      top: r.top + r.height - 4 + 'px',
      left: r.left + r.width - 4 + 'px'
    }"
  ></div>
</ng-container>

<ng-container *ngIf="autofillRect">
  <div
    class="nd-autofill"
    [ngStyle]="{
      top: autofillRect.top + 'px',
      left: autofillRect.left + 'px',
      width: autofillRect.width + 'px',
      height: autofillRect.height + 'px'
    }"
  ></div>
</ng-container>
