// libs/lyra-sheet-react/src/lib/components/actions/MergeDropdown.tsx
import { ReactComponent as Merge } from '../../icons/merge-cells.svg';
import { ReactComponent as Split } from '../../icons/split-cells.svg';
import { useEffect, useState } from 'react';
import { useLyraSheetCore } from '../../container-context';
import { MergeController } from '@lyra-sheet/core';

export function LyraSheetMergeDropdown() {
  const controller = useLyraSheetCore(MergeController);
  const [hasMerge, setHasMerge] = useState(false);

  useEffect(() => {
    controller.hasMerge$.subscribe((res) => setHasMerge(res));
    controller.onInit();
  });

  function applyMerge() {
    controller.applyMerge();
  }

  return (
    <div
      className={'lyra-sheet-toolbar-item lyra-sheet-dropdown merge'}
      onClick={applyMerge}
    >
      {hasMerge ? <Split></Split> : <Merge></Merge>}
    </div>
  );
}

// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/merge-dropdown/merge-dropdown.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import { BaseContainer } from '../../../../services/_base_container';
import { MergeController } from '@lyra-sheet/core';

@Component({
  selector: 'lyra-sheet-merge-dropdown',
  templateUrl: './merge-dropdown.component.html',
  styleUrls: ['./merge-dropdown.component.scss'],
  host: {
    class: 'lyra-sheet-dropdown merge',
  },
})
export class MergeDropdownComponent implements OnInit {
  controller: MergeController;
  constructor(private c: BaseContainer) {
    this.controller = c.mergeController;
  }

  @HostListener('click')
  onClick(): void {
    this.controller.applyMerge();
  }

  ngOnInit() {
    this.controller.onInit();
  }
}

<i class="merge-icon" [class.split-icon]="controller.hasMerge$ | async"></i>
