// libs/lyra-sheet-angular/src/lib/components/color-palette/color-palette.component.ts
import { Component, Output, EventEmitter, ElementRef } from '@angular/core';
import { COLOR_PALETTE } from '@lyra-sheet/core';

@Component({
  selector: 'lyra-sheet-color-palette',
  templateUrl: './color-palette.component.html',
  styleUrls: ['./color-palette.component.scss'],
})
export class ColorPaletteComponent {
  @Output() chosenColor = new EventEmitter<string>();

  colors = COLOR_PALETTE;

  constructor(private el: ElementRef) {
    el.nativeElement.onmousedown = (evt: MouseEvent) => evt.preventDefault();
  }

  chooseColor(color: string): void {
    this.chosenColor.emit(color);
  }
}

// libs/lyra-sheet-react/src/lib/components/ColorPalette.tsx
import { COLOR_PALETTE } from '@lyra-sheet/core';

export function LyraSheetColorPalette(prop: {
  chosenColor: (color: string) => void;
}) {
  return (
    <div onMouseDown={(evt) => evt.preventDefault()}>
      <table>
        <tbody>
          {COLOR_PALETTE.map((cg) => (
            <tr>
              {cg.map((c) => (
                <td>
                  <div
                    className={'color-item'}
                    style={{ backgroundColor: c }}
                    onClick={() => prop.chosenColor(c)}
                  ></div>
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
