// projects/ngx-datasheet/src/lib/components/masker/masker.component.ts
import {
  Component,
  ElementRef,
  HostBinding,
  HostListener,
  OnInit,
  Renderer2,
} from '@angular/core';
import { Subject } from 'rxjs';
import { map, tap, throttleTime } from 'rxjs/operators';
import { EditorService } from '../editor/editor.service';
import { ScrollingService } from '../../core/scrolling.service';
import { SelectorsService } from '../../core/selectors.service';
import { ConfigService } from '../../core/config.service';

@Component({
  selector: 'nd-masker',
  templateUrl: './masker.component.html',
  styleUrls: ['./masker.component.less'],
})
export class MaskerComponent implements OnInit {
  @HostBinding('class.nd-editor-mask') enabled = true;
  private wheel$ = new Subject<WheelEvent>();

  constructor(
    private hostEl: ElementRef<HTMLDivElement>,
    private renderer: Renderer2,
    private configService: ConfigService,
    private editorService: EditorService,
    private scrollingService: ScrollingService,
    public selectorRangeService: SelectorsService,
  ) {}

  @HostListener('wheel', ['$event'])
  onWheel(evt: WheelEvent): void {
    this.wheel$.next(evt);
  }

  ngOnInit(): void {
    this.wheel$
      .asObservable()
      .pipe(
        tap((evt) => evt.preventDefault()),
        throttleTime(20),
        map((evt) => this.editorService.calcNextStepDelta(evt)),
      )
      .subscribe(({ hDelta, vDelta }) => {
        if (vDelta !== undefined) {
          this.scrollingService.vScrollbarShouldGoto.next(vDelta);
        }
        if (hDelta !== undefined) {
          this.scrollingService.hScrollbarShouldGoto.next(hDelta);
        }
      });
  }
}

<div #contentZone class="nd-selector-container">
  <ng-container *ngFor="let r of selectorRangeService.rects">
    <div
      class="nd-selector"
      [ngStyle]="{
        top: r.top + 'px',
        left: r.left + 'px',
        width: r.width + 'px',
        height: r.height + 'px'
      }"
    ></div>
    <div
      class="nd-selector-autofill"
      [ngStyle]="{
        top: r.top + r.height - 4 + 'px',
        left: r.left + r.width - 4 + 'px'
      }"
    ></div>
  </ng-container>
</div>

// libs/lyra-sheet-react/src/lib/components/Masker.tsx
import { useLayoutEffect, useRef } from 'react';
import { useLyraSheetCore } from '../container-context';
import {
  ConfigService,
  EditorService,
  ElementRefService,
  ScrollingService,
} from '@lyra-sheet/core';
import { LyraSheetSelectorContainer } from './SelectorContainer';
import { fromEvent } from 'rxjs';
import { map, tap, throttleTime } from 'rxjs/operators';

export function LyraSheetMasker() {
  const maskRef = useRef(null);
  const elementRefService = useLyraSheetCore(ElementRefService);
  const scrollingService = useLyraSheetCore(ScrollingService);
  const editorService = useLyraSheetCore(EditorService);

  useLayoutEffect(() => {
    elementRefService.initMask(maskRef.current!);

    fromEvent<WheelEvent>(maskRef.current!, 'wheel')
      .pipe(
        tap((evt) => evt.preventDefault()),
        throttleTime(20),
        map((evt) => editorService.calcNextStepDelta(evt)),
      )
      .subscribe(({ hDelta, vDelta }) => {
        if (vDelta !== undefined) {
          scrollingService.vScrollbarShouldGoto.next(vDelta);
        }
        if (hDelta !== undefined) {
          scrollingService.hScrollbarShouldGoto.next(hDelta);
        }
      });
  }, []);

  return (
    <div className={'lyra-sheet-editor-mask'} ref={maskRef}>
      <LyraSheetSelectorContainer></LyraSheetSelectorContainer>
    </div>
  );
}
