// libs/lyra-sheet-angular/src/lib/components/resizer-row/resizer-row.component.ts
import { Component, ElementRef, OnInit } from '@angular/core';
import { ResizerThickness } from '@lyra-sheet/core';
import { BaseContainer } from '../../services/_base_container';

@Component({
  selector: 'lyra-sheet-resizer-row',
  templateUrl: './resizer-row.component.html',
  styleUrls: ['./resizer-row.component.scss'],
  host: {
    class: 'lyra-sheet-resizer lyra-sheet-resizer-row',
  },
})
export class ResizerRowComponent implements OnInit {
  readonly staticStyle = {
    height: `${ResizerThickness}px`,
    width: `${this.c.configService.ciw}px`,
  };

  readonly lineStyle = {
    width: `calc(100% - ${this.c.configService.ciw}px)`,
    transform: `translateY(-${Math.ceil(ResizerThickness / 2)}px)`,
  };
  constructor(private el: ElementRef<HTMLElement>, public c: BaseContainer) {}

  ngOnInit(): void {
    this.c.resizerService.rowResizer$.subscribe((top) => {
      if (top === null) {
        this.el.nativeElement.style.display = 'none';
      } else {
        this.el.nativeElement.style.display = 'block';
        this.el.nativeElement.style.top = `${top}px`;
      }
    });
  }
}

<div class="lyra-sheet-resizer-header" [ngStyle]="staticStyle"></div>
<div
  *ngIf="c.mouseEventService.isRowResizing$.value"
  class="lyra-sheet-resizer-row-line"
  [ngStyle]="lineStyle"
></div>

// libs/lyra-sheet-react/src/lib/components/ResizerRow.tsx
import { useLayoutEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../container-context';
import {
  ConfigService,
  ElementRefService,
  MouseEventService,
  ResizerService,
  ResizerThickness,
} from '@lyra-sheet/core';

export function LyraSheetResizerRow() {
  const resizerRef = useRef<HTMLDivElement>(null);
  const resizerService = useLyraSheetCore(ResizerService);
  const configService = useLyraSheetCore(ConfigService);
  const elementRefService = useLyraSheetCore(ElementRefService);
  const mouseEventService = useLyraSheetCore(MouseEventService);

  const [isRowResizing, setIsRowResizing] = useState(false);

  const staticStyle = {
    height: `${ResizerThickness}px`,
    width: `${configService.ciw}px`,
  };

  const lineStyle = {
    width: `calc(100% - ${configService.ciw}px)`,
    transform: `translateY(-${Math.ceil(ResizerThickness / 2)}px)`,
  };

  useLayoutEffect(() => {
    mouseEventService.isRowResizing$.subscribe((res) => setIsRowResizing(res));
    elementRefService.initRowResizer(resizerRef.current!);
    resizerService.rowResizer$.subscribe((top) => {
      if (top === null) {
        resizerRef.current!.style.display = 'none';
      } else {
        resizerRef.current!.style.display = 'block';
        resizerRef.current!.style.top = `${top}px`;
      }
    });
  }, []);
  return (
    <div
      className={'lyra-sheet-resizer lyra-sheet-resizer-row'}
      ref={resizerRef}
    >
      <div className={'lyra-sheet-resizer-header'} style={staticStyle}></div>
      {isRowResizing ? (
        <div className={'lyra-sheet-resizer-row-line'} style={lineStyle}></div>
      ) : null}
    </div>
  );
}
