// projects/ngx-datasheet/src/lib/components/resizer-col/resizer-col.component.ts
import { Component, ElementRef, HostListener, OnInit } from '@angular/core';
import { ResizerService } from '../../service/resizer.service';
import { ResizerThickness } from '../../constants';
import { ConfigService } from '../../core/config.service';
import { MouseEventService } from '../../service/mouse-event.service';

@Component({
  selector: 'nd-resizer-col',
  templateUrl: './resizer-col.component.html',
  styleUrls: ['./resizer-col.component.less'],
  host: {
    class: 'nd-resizer nd-resizer-col',
  },
})
export class ResizerColComponent implements OnInit {
  readonly headerStaticStyle = {
    width: `${ResizerThickness}px`,
    height: `${this.configService.rih}px`,
  };

  readonly lineStyle = {
    height: `calc(100% - ${this.configService.rih}px)`,
    transform: `translateX(${Math.floor(ResizerThickness / 2)}px)`,
  };
  constructor(
    private el: ElementRef<HTMLElement>,
    private resizerService: ResizerService,
    private configService: ConfigService,
    public mouseEventService: MouseEventService,
  ) {}

  ngOnInit(): void {
    this.resizerService.colResizer$.subscribe((left) => {
      if (left === null) {
        this.el.nativeElement.style.display = 'none';
      } else {
        this.el.nativeElement.style.display = 'block';
        this.el.nativeElement.style.left = `${left}px`;
      }
    });
  }
}

<div class="nd-resizer-header" [ngStyle]="headerStaticStyle"></div>
<div
  *ngIf="mouseEventService.isColResizing"
  class="nd-resizer-col-line"
  [ngStyle]="lineStyle"
></div>

// libs/lyra-sheet-react/src/lib/components/ResizerCol.tsx
import {
  Component,
  createRef,
  RefObject,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from 'react';
import {
  ConfigService,
  ElementRefService,
  MouseEventService,
  ResizerService,
  ResizerThickness,
} from '@lyra-sheet/core';
import { c, useLyraSheetCore } from '../container-context';

export function LyraSheetResizerCol() {
  const resizerRef = useRef<HTMLDivElement>(null);
  const resizerService = useLyraSheetCore(ResizerService);
  const configService = useLyraSheetCore(ConfigService);
  const elementRefService = useLyraSheetCore(ElementRefService);
  const mouseEventService = useLyraSheetCore(MouseEventService);

  const [isColResizing, setIsColResizing] = useState(false);

  const headerStaticStyle = {
    width: `${ResizerThickness}px`,
    height: `${configService.rih}px`,
  };

  const lineStyle = {
    height: `calc(100% - ${configService.rih}px)`,
    transform: `translateX(${Math.floor(ResizerThickness / 2)}px)`,
  };

  useLayoutEffect(() => {
    mouseEventService.isColResizing$.subscribe((res) => setIsColResizing(res));
    elementRefService.initColResizer(resizerRef.current!);
    resizerService.colResizer$.subscribe((left) => {
      if (left === null) {
        resizerRef.current!.style.display = 'none';
      } else {
        resizerRef.current!.style.display = 'block';
        resizerRef.current!.style.left = `${left}px`;
      }
    });
  }, []);

  return (
    <div
      className={'lyra-sheet-resizer lyra-sheet-resizer-col'}
      ref={resizerRef}
    >
      <div
        className={'lyra-sheet-resizer-header'}
        style={headerStaticStyle}
      ></div>
      {isColResizing ? (
        <div className={'lyra-sheet-resizer-col-line'} style={lineStyle}></div>
      ) : null}
    </div>
  );
}
