// libs/lyra-sheet-angular/src/lib/components/rich-text-input/rich-text-input.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import { RichTextInputController } from '@lyra-sheet/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { BaseContainer } from '../../services/_base_container';

@Component({
  selector: 'lyra-sheet-rich-text-input',
  templateUrl: './rich-text-input.component.html',
  styleUrls: ['./rich-text-input.component.scss'],
  host: {
    class: 'lyra-sheet-rich-text-input',
  },
})
export class RichTextInputComponent implements AfterViewInit {
  richTextInputController: RichTextInputController;
  @ViewChild('editableZone') editableZone!: ElementRef<HTMLDivElement>;
  html: SafeHtml = '';

  constructor(
    private c: BaseContainer,
    private hostEl: ElementRef<HTMLElement>,
    private domSanitizer: DomSanitizer,
  ) {
    this.richTextInputController = this.c.richTextInputController;
  }

  ngAfterViewInit(): void {
    this.richTextInputController.mount(
      this.hostEl.nativeElement,
      this.editableZone.nativeElement,
    );
    this.richTextInputController.html$
      .asObservable()
      .subscribe(
        (res) => (this.html = this.domSanitizer.bypassSecurityTrustHtml(res)),
      );
  }
}

<div
  #editableZone
  class="lyra-sheet-rich-text-input-area"
  contenteditable="true"
  [innerHTML]="html"
></div>

// libs/lyra-sheet-react/src/lib/components/RichTextInput.tsx
import { useLayoutEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../container-context';
import { RichTextInputController } from '@lyra-sheet/core';

export function LyraSheetRichTextInput() {
  const hostRef = useRef(null);
  const editableZoneRef = useRef<HTMLDivElement>(null);
  const controller = useLyraSheetCore(RichTextInputController);
  useLayoutEffect(() => {
    controller.mount(hostRef.current!, editableZoneRef.current!);
    controller.html$.subscribe((res) => {
      editableZoneRef.current!.innerHTML = res;
    });
  }, []);
  return (
    <div className={'lyra-sheet-rich-text-input'} ref={hostRef}>
      <div
        ref={editableZoneRef}
        className={'lyra-sheet-rich-text-input-area'}
        contentEditable={true}
      ></div>
    </div>
  );
}
