// libs/lyra-sheet-angular/src/lib/components/tabs/tabs.component.ts
import {
  ChangeDetectorRef,
  Component,
  ElementRef,
  Input,
  ViewChild,
} from '@angular/core';
import {
  DataService,
  HistoryService,
  SheetService,
  TabsController,
  ViewRangeService,
} from '@lyra-sheet/core';
import { BaseContainer } from '../../services/_base_container';

@Component({
  selector: 'lyra-sheet-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.scss'],
  host: { class: 'lyra-sheet-tabs' },
})
export class TabsComponent {
  @Input() tabs: SheetService[] = [];
  @ViewChild('nameInput') nameInput!: ElementRef<HTMLInputElement>;
  tabsController: TabsController;
  public dataService: DataService;
  private viewRangeService: ViewRangeService;
  private historyService: HistoryService;
  constructor(private c: BaseContainer, private cd: ChangeDetectorRef) {
    this.dataService = this.c.dataService;
    this.viewRangeService = this.c.viewRangeService;
    this.historyService = this.c.historyService;
    this.tabsController = this.c.tabsController;
  }

  editSheetName(index: number): void {
    this.tabsController.editSheetName(index);
    this.cd.detectChanges();
    this.nameInput.nativeElement.select();
  }
}

<div
  *ngFor="let sheet of tabs; index as i"
  class="lyra-sheet-tab"
  [class.selected]="sheet.selected"
  (click)="tabsController.selectSheet(i)"
  (dblclick)="editSheetName(i)"
>
  <input
    #nameInput
    class="name-input"
    type="text"
    *ngIf="i === (tabsController.editingIndex$ | async); else displayMode"
    [value]="sheet.name"
    (keydown.enter)="tabsController.triggerBlur($event)"
    (blur)="tabsController.updateSheetName($event, i)"
  />
  <ng-template #displayMode>
    <span>{{ sheet.name }}</span>
  </ng-template>
</div>
<div class="lyra-sheet-tab" (click)="tabsController.addSheet()">+</div>

// libs/lyra-sheet-react/src/lib/components/Tabs.tsx
import { useLayoutEffect, useRef, useState } from 'react';
import { DataService, SheetService, TabsController } from '@lyra-sheet/core';
import { useLyraSheetCore } from '../container-context';

export function LyraSheetTabs() {
  const tabsController = useLyraSheetCore(TabsController);
  const dataService = useLyraSheetCore(DataService);

  const inputRef = useRef<HTMLInputElement>(null);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [tabs, setTabs] = useState<SheetService[]>(dataService.sheets);

  useLayoutEffect(() => {
    tabsController.editingIndex$.subscribe((res) => {
      setEditingIndex(res);
      setTimeout(() => inputRef.current?.select());
    });
    tabsController.tabs$.subscribe((res) => setTabs([...res]));
  }, []);

  const dbClick = (i: number) => {
    tabsController.editSheetName(i);
  };

  return (
    <div className={'lyra-sheet-tabs'}>
      {tabs.map((sheet, i) => (
        <div
          key={i}
          className={`lyra-sheet-tab ${sheet.selected ? 'selected' : ''}`}
          onClick={() => tabsController.selectSheet(i)}
          onDoubleClick={() => dbClick(i)}
        >
          {i === editingIndex ? (
            <input
              ref={inputRef}
              className={'name-input'}
              type="text"
              defaultValue={sheet.name}
              onKeyDown={(evt) =>
                evt.key === 'Enter' && tabsController.triggerBlur(evt as any)
              }
              onBlur={(evt) => tabsController.updateSheetName(evt as any, i)}
            />
          ) : (
            <span>{sheet.name}</span>
          )}
        </div>
      ))}

      <div
        className={'lyra-sheet-tab'}
        onClick={() => tabsController.addSheet()}
      >
        +
      </div>
    </div>
  );
}
