// libs/lyra-sheet-react/src/lib/components/actions/ItalicAction.tsx
import { ReactComponent as Italic } from '../../icons/text-italic.svg';
import { useEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../../container-context';
import { FontItalicController } from '@lyra-sheet/core';

export function LyraSheetItalicAction() {
  const ref = useRef<HTMLDivElement>(null);
  const controller = useLyraSheetCore(FontItalicController);
  const [isItalic, setIsItalic] = useState(false);

  useEffect(() => {
    controller.value$.subscribe((res) => setIsItalic(res));
    controller.onInit();
    ref.current!.onmousedown = (evt) => evt.preventDefault();
  }, []);

  function applyTextItalic() {
    controller.toggle();
  }

  return (
    <div
      className={`lyra-sheet-toolbar-item ${isItalic ? 'activated' : ''}`}
      ref={ref}
      onClick={() => applyTextItalic()}
    >
      <Italic className={'lyra-sheet-toolbar-icon'}></Italic>
    </div>
  );
}

// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/italic-action/italic-action.component.ts
import {
  Component,
  ElementRef,
  HostBinding,
  HostListener,
  OnInit,
} from '@angular/core';
import { BaseContainer } from '../../../../services/_base_container';
import { FontItalicController } from '@lyra-sheet/core';

@Component({
  selector: 'lyra-sheet-italic-action',
  templateUrl: './italic-action.component.html',
  styleUrls: ['./italic-action.component.scss'],
})
export class ItalicActionComponent implements OnInit {
  controller: FontItalicController;
  @HostBinding('class.activated') isItalicNow = false;

  constructor(private el: ElementRef, private c: BaseContainer) {
    this.controller = c.fontItalicController;
  }

  @HostListener('click')
  onClick(): void {
    this.controller.toggle();
  }

  ngOnInit(): void {
    this.controller.value$.subscribe((res) => (this.isItalicNow = res));
    this.controller.onInit();
    this.el.nativeElement.onmousedown = (evt: MouseEvent) =>
      evt.preventDefault();
  }
}

<i class="lyra-sheet-toolbar-icon italic-icon"></i>
