// libs/lyra-sheet-react/src/lib/components/ContextMenu.tsx
import { useLayoutEffect, useRef, useState } from 'react';
import { useLyraSheetCore } from '../container-context';
import { ContextMenuController, ContextMenus } from '@lyra-sheet/core';
import { LyraSheetDivider } from './Divider';
import { LyraSheetDropdownBar } from './DropdownBar';

export function LyraSheetContextMenu() {
  const menuRef = useRef<HTMLDivElement>(null);
  const contextMenuController = useLyraSheetCore(ContextMenuController);

  const [menus, setMenus] = useState<ContextMenus>([]);
  const [activatedSubMenus, setActivatedSubMenus] = useState<ContextMenus>([]);
  const [offsetLeft, setOffsetLeft] = useState(0);
  const [offsetTop, setOffsetTop] = useState(0);

  useLayoutEffect(() => {
    contextMenuController.mount(menuRef.current!);
    contextMenuController.onInit();
    contextMenuController.menus$.subscribe((res) => setMenus(res));
    contextMenuController.activatedSubMenus$.subscribe((res) =>
      setActivatedSubMenus(res),
    );
    contextMenuController.offsetTop$.subscribe((res) => setOffsetTop(res));
    contextMenuController.offsetLeft$.subscribe((res) => setOffsetLeft(res));
  }, []);

  return (
    <div className={'lyra-sheet-contextmenu'} ref={menuRef}>
      <div className={'lyra-sheet-contextmenu-tree'}>
        {menus.map((m) => {
          if (m === 'DIVIDER') {
            return (
              <LyraSheetDivider direction={'horizontal'}></LyraSheetDivider>
            );
          } else if (m.action) {
            return (
              <LyraSheetDropdownBar
                desc={m.desc || ' '}
                onMouseEnter={(evt) =>
                  contextMenuController.showSubMenus(evt as any)
                }
                onClick={m.action}
              >
                {m.label}
              </LyraSheetDropdownBar>
            );
          } else {
            return (
              <LyraSheetDropdownBar
                desc={'>'}
                onMouseEnter={(evt) =>
                  contextMenuController.showSubMenus(evt as any, m.children!)
                }
              >
                {m.label}
              </LyraSheetDropdownBar>
            );
          }
        })}
      </div>
      <div
        className={'lyra-sheet-contextmenu-tree'}
        style={{
          transform: 'translate(' + offsetLeft + 'px,' + offsetTop + 'px)',
        }}
      >
        {activatedSubMenus.map((subMenu) =>
          subMenu !== 'DIVIDER' && subMenu.action ? (
            <LyraSheetDropdownBar
              onClick={subMenu.action}
              desc={subMenu.desc || ' '}
            >
              {subMenu.label}
            </LyraSheetDropdownBar>
          ) : null,
        )}
      </div>
    </div>
  );
}

// libs/lyra-sheet-angular/src/lib/components/contextmenu/contextmenu.component.ts
import { Component, ElementRef, HostBinding, OnInit } from '@angular/core';
import { ContextMenuController } from '@lyra-sheet/core';
import { BaseContainer } from '../../services/_base_container';

@Component({
  selector: 'lyra-sheet-contextmenu',
  templateUrl: './contextmenu.component.html',
  styleUrls: ['./contextmenu.component.scss'],
})
export class ContextmenuComponent implements OnInit {
  contextMenuController: ContextMenuController;
  @HostBinding('class.lyra-sheet-contextmenu') h = true;

  constructor(private c: BaseContainer, private el: ElementRef<HTMLElement>) {
    this.contextMenuController = c.contextMenuController;
    this.contextMenuController.mount(this.el.nativeElement);
  }

  ngOnInit(): void {
    this.contextMenuController.onInit();
  }
}

<div class="lyra-sheet-contextmenu-tree">
  <ng-container *ngFor="let menu of contextMenuController.menus$ | async">
    <ng-container *ngIf="menu !== 'DIVIDER'; else dividerTmpl">
      <lyra-sheet-dropdown-bar
        *ngIf="menu.action; else navItem"
        (mouseenter)="contextMenuController.showSubMenus($event)"
        (click)="menu.action()"
        [desc]="menu.desc || ' '"
      >
        {{ menu.label }}
      </lyra-sheet-dropdown-bar>
      <ng-template #navItem>
        <lyra-sheet-dropdown-bar
          [desc]="'>'"
          (mouseenter)="
            contextMenuController.showSubMenus($event, menu.children!)
          "
        >
          {{ menu.label }}
        </lyra-sheet-dropdown-bar>
      </ng-template>
    </ng-container>
    <ng-template #dividerTmpl>
      <lyra-sheet-divider direction="horizontal"></lyra-sheet-divider>
    </ng-template>
  </ng-container>
</div>
<div
  class="lyra-sheet-contextmenu-tree"
  [ngStyle]="{
    transform:
      'translate(' +
      (contextMenuController.offsetLeft$ | async) +
      'px,' +
      (contextMenuController.offsetTop$ | async) +
      'px)'
  }"
>
  <ng-container
    *ngFor="let subMenu of contextMenuController.activatedSubMenus$ | async"
  >
    <lyra-sheet-dropdown-bar
      *ngIf="subMenu !== 'DIVIDER' && subMenu.action"
      (click)="subMenu.action()"
      [desc]="subMenu.desc || ' '"
    >
      {{ subMenu.label }}
    </lyra-sheet-dropdown-bar>
  </ng-container>
</div>
