// libs/lyra-sheet-react/src/lib/components/ScrollbarV.tsx
import { useEffect, useLayoutEffect, useRef } from 'react';
import {
  ConfigService,
  DataService,
  RenderProxyService,
  ScrollingService,
  ViewRangeService,
} from '@lyra-sheet/core';
import { useLyraSheetCore } from '../container-context';
import { fromEvent } from 'rxjs';

function setStyle(el: HTMLElement, attr: any, val: string) {
  el.style[attr] = val;
}

export function ScrollbarV() {
  const scrollbarRef = useRef<HTMLDivElement>(null);
  const mockerRef = useRef<HTMLDivElement>(null);
  const configService = useLyraSheetCore(ConfigService);
  const dataService = useLyraSheetCore(DataService);
  const scrolling = useLyraSheetCore(ScrollingService);
  const viewRangeService = useLyraSheetCore(ViewRangeService);
  const renderProxyService = useLyraSheetCore(RenderProxyService);

  useLayoutEffect(() => {
    // onInit
    configService.config$.subscribe(({ row }) => {
      setStyle(scrollbarRef.current!, 'top', `${row.indexHeight - 0.5}px`);
      setStyle(
        scrollbarRef.current!,
        'width',
        `${configService.scrollbarThick}px`,
      );
      setStyle(
        scrollbarRef.current!,
        'bottom',
        `${configService.scrollbarThick + configService.tabBarHeight}px`,
      );
    });
    scrolling.vScrollbarShouldGoto.asObservable().subscribe((vDelta) => {
      const vScrollNEl = scrollbarRef.current!;
      const top = vDelta === 0 ? 0 : vScrollNEl.scrollTop + vDelta;
      vScrollNEl.scrollTo({ top });
    });

    // afterViewInit
    renderProxyService.shouldRender$.subscribe(() => {
      mockerRef.current!.style.height = `${dataService.selectedSheet.getTotalHeight()}px`;
    });

    fromEvent<MouseEvent>(scrollbarRef.current!, 'scroll').subscribe((evt) => {
      const { scrollTop } = evt.target as HTMLElement;
      const targetRi = dataService.selectedSheet.getRowIndex(scrollTop);
      // NOTICE:
      // `setRowIndex` should be called after `setRowRange`
      // as scroll will trigger selectors rerender, rerender requires latest viewRange
      // related to /components/selector-container/selector-container.component.ts line 39
      viewRangeService.setRowRange(targetRi, scrollTop);
      scrolling.setRowIndex(targetRi);
      dataService.rerender();
    });
  }, []);
  return (
    <div
      className={'lyra-sheet-scrollbar lyra-sheet-scrollbar-v'}
      ref={scrollbarRef}
    >
      <div
        ref={mockerRef}
        className={'lyra-sheet-scrollbar-v-mock'}
        style={{ width: '1px', height: 0 }}
      ></div>
    </div>
  );
}

// projects/ngx-datasheet/src/lib/components/scrollbar-v/scrollbar-v.component.ts
import {
  Component,
  ElementRef,
  HostListener,
  OnInit,
  Renderer2,
  ViewChild,
  AfterViewInit,
} from '@angular/core';
import { ConfigService } from '../../core/config.service';
import { DataService } from '../../core/data.service';
import { ScrollingService } from '../../core/scrolling.service';
import { ViewRangeService } from '../../core/view-range.service';
import { RenderProxyService } from '../../service/render-proxy.service';

@Component({
  selector: 'nd-scrollbar-v',
  templateUrl: './scrollbar-v.component.html',
  styleUrls: ['./scrollbar-v.component.less'],
  host: { class: 'nd-scrollbar nd-scrollbar-v' },
})
export class ScrollbarVComponent implements OnInit, AfterViewInit {
  @ViewChild('mocker') mocker!: ElementRef<HTMLElement>;
  constructor(
    private el: ElementRef<HTMLElement>,
    private render: Renderer2,
    private configService: ConfigService,
    private dataService: DataService,
    private scrolling: ScrollingService,
    private viewRangeService: ViewRangeService,
    private renderProxyService: RenderProxyService,
  ) {}

  //
  @HostListener('scroll', ['$event'])
  onScroll(evt: MouseEvent): void {
    const { scrollTop } = evt.target as HTMLElement;
    const targetRi = this.dataService.selectedSheet.getRowIndex(scrollTop);
    // NOTICE:
    // `setRowIndex` should be called after `setRowRange`
    // as scroll will trigger selectors rerender, rerender requires latest viewRange
    // related to /components/selector-container/selector-container.component.ts line 39
    this.viewRangeService.setRowRange(targetRi, scrollTop);
    this.scrolling.setRowIndex(targetRi);
    this.dataService.rerender();
  }

  ngOnInit(): void {
    this.configService.config$.subscribe(({ row }) => {
      this.render.setStyle(
        this.el.nativeElement,
        'top',
        `${row.indexHeight - 0.5}px`,
      );
      this.render.setStyle(
        this.el.nativeElement,
        'width',
        `${this.configService.scrollbarThick}px`,
      );
      this.render.setStyle(
        this.el.nativeElement,
        'bottom',
        `${
          this.configService.scrollbarThick + this.configService.tabBarHeight
        }px`,
      );
    });
    this.scrolling.vScrollbarShouldGoto.asObservable().subscribe((vDelta) => {
      const vScrollNEl = this.el.nativeElement;
      const top = vDelta === 0 ? 0 : vScrollNEl.scrollTop + vDelta;
      vScrollNEl.scrollTo({ top });
    });
  }

  ngAfterViewInit(): void {
    this.renderProxyService.shouldRender$.subscribe(() => {
      this.mocker.nativeElement.style.height = `${this.dataService.selectedSheet.getTotalHeight()}px`;
    });
  }
}

<div #mocker class="nd-scrollbar-v-mock" style="width: 1px; height: 0"></div>
