// libs/lyra-sheet-react/src/lib/components/actions/BorderDropdown.tsx
import { ReactElement, useRef, useState } from 'react';
import { LyraSheetDropdown } from '../Dropdown';
import { LyraSheetColorPalette } from '../ColorPalette';
import {
  BorderController,
  BorderSelection,
  BorderType,
} from '@lyra-sheet/core';
import { useLyraSheetCore } from '../../container-context';
import { ReactComponent as BorderAll } from '../../icons/border_all.svg';
import { ReactComponent as BorderInner } from '../../icons/border_inner.svg';
import { ReactComponent as BorderHorizontal } from '../../icons/border_horizontal.svg';
import { ReactComponent as BorderVertical } from '../../icons/border_vertical.svg';
import { ReactComponent as BorderOuter } from '../../icons/border_outer.svg';
import { ReactComponent as BorderLeft } from '../../icons/border_left.svg';
import { ReactComponent as BorderTop } from '../../icons/border_top.svg';
import { ReactComponent as BorderRight } from '../../icons/border_right.svg';
import { ReactComponent as BorderBottom } from '../../icons/border_bottom.svg';
import { ReactComponent as BorderClear } from '../../icons/border_clear.svg';
import { ReactComponent as Pencil } from '../../icons/写作_write.svg';
import { ReactComponent as DividingLine } from '../../icons/分割线_dividing-line.svg';
import { LyraSheetDropdownBar } from '../DropdownBar';

export function LyraSheetBorderDropdown() {
  const controller = useLyraSheetCore(BorderController);
  const hostRef = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState<boolean>(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  const [borderColorOpen, setBorderColorOpen] = useState<boolean>(false);
  const handleBorderColorOpen = () => setBorderColorOpen(true);
  const handleBorderColorClose = () => setBorderColorOpen(false);

  const [borderTypeOpen, setBorderTypeOpen] = useState<boolean>(false);
  const handleBorderTypeOpen = () => setBorderTypeOpen(true);
  const handleBorderTypeClose = () => setBorderTypeOpen(false);

  const borders: Array<{ type: BorderSelection; icon: ReactElement }> = [
    { type: 'all', icon: <BorderAll className={'lyra-sheet-toolbar-icon'} /> },
    {
      type: 'inner',
      icon: <BorderInner className={'lyra-sheet-toolbar-icon'} />,
    },
    {
      type: 'horizontal',
      icon: <BorderHorizontal className={'lyra-sheet-toolbar-icon'} />,
    },
    {
      type: 'vertical',
      icon: <BorderVertical className={'lyra-sheet-toolbar-icon'} />,
    },
    {
      type: 'outer',
      icon: <BorderOuter className={'lyra-sheet-toolbar-icon'} />,
    },
    {
      type: 'left',
      icon: <BorderLeft className={'lyra-sheet-toolbar-icon'} />,
    },
    { type: 'top', icon: <BorderTop className={'lyra-sheet-toolbar-icon'} /> },
    {
      type: 'right',
      icon: <BorderRight className={'lyra-sheet-toolbar-icon'} />,
    },
    {
      type: 'bottom',
      icon: <BorderBottom className={'lyra-sheet-toolbar-icon'} />,
    },
    {
      type: 'clear',
      icon: <BorderClear className={'lyra-sheet-toolbar-icon'} />,
    },
  ];

  function applyBorder(type: BorderSelection) {
    controller.applyBorder(type);
    handleClose();
  }

  function onSelectColor(color: string) {
    controller.onSelectColor(color);
    handleBorderColorClose();
  }

  function onSelectType(borderType: BorderType): void {
    controller.onSelectType(borderType);
    handleBorderTypeClose();
  }

  return (
    <div className={'lyra-sheet-toolbar-item'} ref={hostRef}>
      <LyraSheetDropdown
        isOpen={open}
        label={<BorderAll className={'lyra-sheet-toolbar-icon'}></BorderAll>}
        onClose={handleClose}
        onOpen={handleOpen}
      >
        <div className={'border-dropdown'}>
          <div className={'left-section'}>
            {borders.map((bd) => (
              <div
                className={'lyra-sheet-dropdown-option'}
                onClick={() => applyBorder(bd.type)}
                key={bd.type}
              >
                {bd.icon}
              </div>
            ))}
          </div>
          <div className={'right-section'}>
            <LyraSheetDropdown
              isOpen={borderColorOpen}
              label={
                <div
                  className={'lyra-sheet-dropdown-option'}
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    width: '21px',
                  }}
                >
                  <Pencil className={'lyra-sheet-toolbar-icon'}></Pencil>
                  <div
                    style={{
                      width: '18px',
                      height: '2px',
                      marginTop: '2px',
                      backgroundColor: controller.defaultBorderColor$.value,
                    }}
                  ></div>
                </div>
              }
              onClose={handleBorderColorClose}
              onOpen={handleBorderColorOpen}
            >
              <LyraSheetColorPalette
                chosenColor={onSelectColor}
              ></LyraSheetColorPalette>
            </LyraSheetDropdown>

            <LyraSheetDropdown
              isOpen={borderTypeOpen}
              label={
                <div
                  className={'lyra-sheet-dropdown-option'}
                  style={{ width: '21px' }}
                >
                  <DividingLine className="lyra-sheet-toolbar-icon"></DividingLine>
                </div>
              }
              onClose={handleBorderTypeClose}
              onOpen={handleBorderTypeOpen}
            >
              <LyraSheetDropdownBar
                checked={controller.defaultBorderType$.value === 'thin'}
                onClick={() => onSelectType('thin')}
              >
                <div
                  style={{ width: '50px', height: '1px', background: '#000' }}
                ></div>
              </LyraSheetDropdownBar>
              <LyraSheetDropdownBar
                checked={controller.defaultBorderType$.value === 'medium'}
                onClick={() => onSelectType('medium')}
              >
                <div
                  style={{ width: '50px', height: '2px', background: '#000' }}
                ></div>
              </LyraSheetDropdownBar>
              <LyraSheetDropdownBar
                checked={controller.defaultBorderType$.value === 'bold'}
                onClick={() => onSelectType('bold')}
              >
                <div
                  style={{ width: '50px', height: '3px', background: '#000' }}
                ></div>
              </LyraSheetDropdownBar>
            </LyraSheetDropdown>
          </div>
        </div>
      </LyraSheetDropdown>
    </div>
  );
}

// projects/ngx-datasheet/src/lib/components/toolbar/actions/border-dropdown/border-dropdown.component.ts
import { Component, OnInit } from '@angular/core';
import { BorderType } from '../../../../models';
import { DataService } from '../../../../core/data.service';
import { SelectorsService } from '../../../../core/selectors.service';
import { BorderSelection } from '../../../../core/sheet.service';

@Component({
  selector: 'nd-border-dropdown',
  templateUrl: './border-dropdown.component.html',
  styleUrls: ['./border-dropdown.component.less'],
})
export class BorderDropdownComponent implements OnInit {
  defaultBorderType: BorderType = 'thin';
  defaultBorderColor = '#000000';
  open = false;
  borderTypeOpen = false;
  borderColorOpen = false;
  constructor(
    private dataService: DataService,
    private selectorsService: SelectorsService,
  ) {}

  ngOnInit(): void {}

  applyBorder(type: BorderSelection): void {
    this.selectorsService.selectors.forEach((st) => {
      this.dataService.selectedSheet.applyBorderTo(
        st.range,
        type,
        this.defaultBorderType,
        this.defaultBorderColor,
      );
    });
    this.open = false;
    this.dataService.rerender();
  }

  onSelectType(borderType: BorderType): void {
    this.defaultBorderType = borderType;
    this.borderTypeOpen = false;
  }

  onSelectColor(color: string): void {
    this.defaultBorderColor = color;
    this.borderColorOpen = false;
  }
}

<nd-dropdown [dropdown]="bordersTmpl" [(isOpen)]="open">
  <i class="nd-toolbar-icon border-all-icon"></i>
</nd-dropdown>
<ng-template #bordersTmpl>
  <div class="border-dropdown">
    <div class="left-section">
      <div>
        <div class="nd-toolbar-dropdown-option" (click)="applyBorder('all')">
          <i class="nd-toolbar-icon border-all-icon"></i>
        </div>
        <div class="nd-toolbar-dropdown-option" (click)="applyBorder('inner')">
          <i class="nd-toolbar-icon border-inner-icon"></i>
        </div>
        <div
          class="nd-toolbar-dropdown-option"
          (click)="applyBorder('horizontal')"
        >
          <i class="nd-toolbar-icon border-horizontal-icon"></i>
        </div>
        <div
          class="nd-toolbar-dropdown-option"
          (click)="applyBorder('vertical')"
        >
          <i class="nd-toolbar-icon border-vertical-icon"></i>
        </div>
        <div class="nd-toolbar-dropdown-option" (click)="applyBorder('outer')">
          <i class="nd-toolbar-icon border-outer-icon"></i>
        </div>
      </div>
      <div>
        <div class="nd-toolbar-dropdown-option" (click)="applyBorder('left')">
          <i class="nd-toolbar-icon border-left-icon"></i>
        </div>
        <div class="nd-toolbar-dropdown-option" (click)="applyBorder('top')">
          <i class="nd-toolbar-icon border-top-icon"></i>
        </div>
        <div class="nd-toolbar-dropdown-option" (click)="applyBorder('right')">
          <i class="nd-toolbar-icon border-right-icon"></i>
        </div>
        <div class="nd-toolbar-dropdown-option" (click)="applyBorder('bottom')">
          <i class="nd-toolbar-icon border-bottom-icon"></i>
        </div>
        <div class="nd-toolbar-dropdown-option" (click)="applyBorder('clear')">
          <i class="nd-toolbar-icon border-clear-icon"></i>
        </div>
      </div>
    </div>
    <div class="right-section">
      <nd-dropdown [dropdown]="colorPalette" [(isOpen)]="borderColorOpen">
        <div
          class="nd-toolbar-dropdown-option"
          style="display: flex; flex-direction: column"
        >
          <i class="nd-toolbar-icon pencil-icon"></i>
          <div
            style="width: 20px; height: 2px; margin-top: 2px"
            [ngStyle]="{ backgroundColor: defaultBorderColor }"
          ></div>
        </div>
      </nd-dropdown>
      <nd-dropdown [dropdown]="borderTypeTmpl" [(isOpen)]="borderTypeOpen">
        <div class="nd-toolbar-dropdown-option">
          <i class="nd-toolbar-icon dividing-line-icon"></i>
        </div>
      </nd-dropdown>
    </div>
  </div>
</ng-template>

<ng-template #colorPalette>
  <nd-color-palette (chosenColor)="onSelectColor($event)"></nd-color-palette>
</ng-template>

<ng-template #borderTypeTmpl>
  <div
    class="nd-toolbar-dropdown-bar"
    [class.checked]="defaultBorderType === 'thin'"
    (click)="onSelectType('thin')"
  >
    <div style="width: 50px; height: 1px; background: #000"></div>
  </div>
  <div
    class="nd-toolbar-dropdown-bar"
    [class.checked]="defaultBorderType === 'medium'"
    (click)="onSelectType('medium')"
  >
    <div style="width: 50px; height: 2px; background: #000"></div>
  </div>
  <div
    class="nd-toolbar-dropdown-bar"
    [class.checked]="defaultBorderType === 'bold'"
    (click)="onSelectType('bold')"
  >
    <div style="width: 50px; height: 3px; background: #000"></div>
  </div>
</ng-template>
