// libs/lyra-sheet-react/src/lib/components/actions/FontSizeDropdown.tsx
import { useEffect, useRef, useState } from 'react';
import { LyraSheetDropdown } from '../Dropdown';
import { useLyraSheetCore } from '../../container-context';
import { FontSizeController, FontSizeMenu } from '@lyra-sheet/core';
import { LyraSheetDropdownBar } from '../DropdownBar';

export function LyraSheetFontSizeDropdown() {
  const hostRef = useRef<HTMLDivElement>(null);
  const controller = useLyraSheetCore(FontSizeController);
  const [open, setOpen] = useState<boolean>(false);
  const [curFontSize, setCurFontSize] = useState<number>(9);
  const [menus, setMenus] = useState<FontSizeMenu[]>([]);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  useEffect(() => {
    hostRef.current!.onmousedown = (evt) => evt.preventDefault();
    controller.curFontSize$.subscribe((res) => setCurFontSize(res));
    controller.menus$.subscribe((res) => setMenus(res));
    controller.onInit();
  }, []);

  function applyFontSize(arg: FontSizeMenu) {
    controller.applyFontSize(arg);
    handleClose();
  }

  return (
    <div className={'lyra-sheet-toolbar-item'} ref={hostRef}>
      <LyraSheetDropdown
        isOpen={open}
        label={curFontSize.toString()}
        onClose={handleClose}
        onOpen={handleOpen}
      >
        {menus.map((menu) => (
          <LyraSheetDropdownBar
            key={menu.pt}
            checked={menu.checked}
            onClick={() => applyFontSize(menu)}
          >
            {menu.pt}
          </LyraSheetDropdownBar>
        ))}
      </LyraSheetDropdown>
    </div>
  );
}

// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/font-size-dropdown/font-size-dropdown.component.ts
import { Component, ElementRef, OnInit } from '@angular/core';
import { FontSizeController, FontSizeMenu } from '@lyra-sheet/core';
import { BaseContainer } from '../../../../services/_base_container';

@Component({
  selector: 'lyra-sheet-font-size-dropdown',
  templateUrl: './font-size-dropdown.component.html',
  styleUrls: ['./font-size-dropdown.component.scss'],
})
export class FontSizeDropdownComponent implements OnInit {
  controller: FontSizeController;
  open = false;
  curFontSize!: number;
  menus!: FontSizeMenu[];

  constructor(private el: ElementRef, private c: BaseContainer) {
    this.controller = c.fontSizeController;
  }

  applyFontSize(option: { pt: number; px: number }): void {
    this.controller.applyFontSize(option);
    this.open = false;
  }

  ngOnInit(): void {
    this.el.nativeElement.onmousedown = (evt: MouseEvent) =>
      evt.preventDefault();
    this.controller.curFontSize$.subscribe((res) => (this.curFontSize = res));
    this.controller.menus$.subscribe((res) => (this.menus = res));
    this.controller.onInit();
  }
}

<lyra-sheet-dropdown [dropdown]="sizeTmpl" [(isOpen)]="open">
  {{ curFontSize }}
</lyra-sheet-dropdown>
<ng-template #sizeTmpl>
  <lyra-sheet-dropdown-bar
    *ngFor="let op of menus"
    [checked]="op.checked"
    (click)="applyFontSize(op)"
  >
    {{ op.pt }}
  </lyra-sheet-dropdown-bar>
</ng-template>
