// libs/lyra-sheet-react/src/lib/components/actions/FormatDropdown.tsx
import { LyraSheetDropdown } from '../Dropdown';
import { LyraSheetDropdownBar } from '../DropdownBar';
import { useEffect, useState } from 'react';
import { useLyraSheetCore } from '../../container-context';
import { CellFormat, FormatController } from '@lyra-sheet/core';
import { LyraSheetDivider } from '../Divider';

export function LyraSheetFormatDropdown() {
  const controller = useLyraSheetCore(FormatController);
  const [open, setOpen] = useState<boolean>(false);
  const [controlDisplayLabel, setControlDisplayLabel] = useState<string>('');
  const [items, setItems] = useState<
    Array<
      | {
          fmt: CellFormat;
          label: string;
          desc: string;
          checked: () => boolean;
        }
      | 'DIVIDER'
    >
  >([]);

  useEffect(() => {
    controller.items$.subscribe((res) => setItems(res));
    controller.controlDisplayLabel$.subscribe((res) =>
      setControlDisplayLabel(res),
    );
    controller.onInit();
  }, []);

  function applyFormat(fmt: CellFormat) {
    controller.applyFormat(fmt);
    handleClose();
  }

  function handleOpen() {
    setOpen(true);
  }
  function handleClose() {
    setOpen(false);
  }

  return (
    <div className={'lyra-sheet-toolbar-item'}>
      <LyraSheetDropdown
        label={controlDisplayLabel}
        isOpen={open}
        onOpen={handleOpen}
        onClose={handleClose}
      >
        {items.map((item, index) =>
          item === 'DIVIDER' ? (
            <div style={{ margin: '8px 0' }} key={index}>
              <LyraSheetDivider direction={'horizontal'}></LyraSheetDivider>
            </div>
          ) : (
            <LyraSheetDropdownBar
              key={index}
              desc={item.desc}
              checked={item.checked()}
              onClick={() => applyFormat(item.fmt)}
            >
              {item.label}
            </LyraSheetDropdownBar>
          ),
        )}
      </LyraSheetDropdown>
    </div>
  );
}

// libs/lyra-sheet-angular/src/lib/components/toolbar/actions/format-dropdown/format-dropdown.component.ts
import { Component, OnInit } from '@angular/core';
import { CellFormat, FormatController } from '@lyra-sheet/core';
import { BaseContainer } from '../../../../services/_base_container';

@Component({
  selector: 'lyra-sheet-format-dropdown',
  templateUrl: './format-dropdown.component.html',
  styleUrls: ['./format-dropdown.component.scss'],
})
export class FormatDropdownComponent implements OnInit {
  controller: FormatController;
  controlDisplayLabel!: string;

  isOpen = false;

  items!: Array<
    | {
        fmt: CellFormat;
        label: string;
        desc: string;
        checked: () => boolean;
      }
    | 'DIVIDER'
  >;

  constructor(private c: BaseContainer) {
    this.controller = c.formatController;
  }

  ngOnInit() {
    this.controller.items$.subscribe((res) => (this.items = res));
    this.controller.controlDisplayLabel$.subscribe(
      (res) => (this.controlDisplayLabel = res),
    );
    this.controller.onInit();
  }

  applyFormat(fmt: CellFormat): void {
    this.controller.applyFormat(fmt);
    this.isOpen = false;
  }
}

<lyra-sheet-dropdown [dropdown]="dropdown" [(isOpen)]="isOpen">
  {{ controlDisplayLabel }}
</lyra-sheet-dropdown>
<ng-template #dropdown>
  <ng-container *ngFor="let item of items">
    <lyra-sheet-dropdown-bar
      *ngIf="item !== 'DIVIDER'; else dividerTmpl"
      [desc]="item.desc"
      [checked]="item.checked()"
      (click)="applyFormat(item.fmt)"
    >
      {{ item.label }}
    </lyra-sheet-dropdown-bar>
  </ng-container>
  <ng-template #dividerTmpl>
    <lyra-sheet-divider
      direction="horizontal"
      style="margin: 8px 0"
    ></lyra-sheet-divider>
  </ng-template>
</ng-template>
